server:
  port: 8080

logging:
  level:
    root: DEBUG
    com.aidataquality: DEBUG
    org.springframework.web: DEBUG

app:
  security:
    cors:
      allowed-origins: http://localhost:3000,http://localhost:5173

